# Generated by Django 5.0.4 on 2024-04-26 06:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_customuser_thumbnail"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="bio",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
